### ISSUE TITLE
init firs api nest application in backend dir

### ISSUE THREAD

**Issue by SeyedMostafaHosseinian** [jscoderman/blog-app#3]
init first nest app api service

**Comment by Jafar313** [comment]
Congratulations!
![image](https://user-images.githubusercontent.com/35448804/234461390-ac4e2166-1bd8-47e1-b555-7e08a947d563.png)

**Comment by SeyedMostafaHosseinian** [comment]
> Congratulations! ![image](https://user-images.githubusercontent.com/35448804/234461390-ac4e2166-1bd8-47e1-b555-7e08a947d563.png)

سید جان این issue برای init اپلیکیشن با nest تو دایرکتوری backend عه 😅😅😅
